# Google Cloud Run Configuration
# This file contains the Cloud Run service configuration
# You can deploy this using: gcloud run services replace cloud-run.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: placetory-backoffice
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # VPC settings
        run.googleapis.com/vpc-access-connector: placetory-backoffice-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        
        # Autoscaling
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        
        # Resource allocation
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1"
        
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/placetory-backoffice
        ports:
        - name: http1
          containerPort: 8080
        env:
        # Application settings
        - name: APP_NAME
          value: "Placetory Backoffice"
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: APP_KEY
          value: "base64:YOUR_APP_KEY_HERE"
        - name: APP_URL
          value: "https://placetory-backoffice-PROJECT_ID.a.run.app"
        
        # Logging
        - name: LOG_CHANNEL
          value: "errorlog"
        - name: LOG_LEVEL
          value: "info"
        
        # Database
        - name: DB_CONNECTION
          value: "pgsql"
        - name: DB_HOST
          value: "YOUR_DB_PRIVATE_IP"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "placetory_backoffice"
        - name: DB_USERNAME
          value: "laravel"
        - name: DB_PASSWORD
          value: "YOUR_DB_PASSWORD"
        
        # Redis
        - name: REDIS_HOST
          value: "YOUR_REDIS_HOST"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        
        # Cache and Sessions
        - name: CACHE_DRIVER
          value: "redis"
        - name: SESSION_DRIVER
          value: "redis"
        - name: QUEUE_CONNECTION
          value: "redis"
        
        # Octane
        - name: OCTANE_SERVER
          value: "frankenphp"
        
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        # Health check
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
